### ISSUE TITLE
error logging

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer-build#143] opened 2017-02-27 15:17 UTC
If one of the dependencies has a bad path, its extremely hard to debug, i found that it was able to find the missing files if they are one level up, for example, I get the file not found error when the files are in:
`<link rel="import" src="../src/some-folder/some-file.html">`

but no error when the files are two or more levels deep:

`<link rel="import" src="../../src/some-folder/some-file.html">`

Can we get this fixed? Its pretty hard to track down the bad path if we have 20 odd dependencies.

**Comment by tony19** [comment] 2017-02-27 23:53
This sounds like a duplicate of #88, which was fixed in `polymer-build` [0.7.1](https://github.com/Polymer/polymer-build/blob/master/CHANGELOG.md#071---2017-02-03).

 * Can you re-test with the newest version of `polymer-build` ([0.8.2](https://github.com/Polymer/polymer-build/blob/master/CHANGELOG.md#082---2017-02-24))? You can also check with the latest `polymer-cli` ([0.18.0-pre.10](https://github.com/Polymer/polymer-cli/blob/master/CHANGELOG.md#v0180-pre10-02-21-2017)).
 * If you could still reproduce the issue with the newest versions, can you provide a repro to help narrow down the problem?

**Comment by jay8t6** [comment] 2017-02-28 01:47
Thanks, I'll give it a try. You're right, I must have been using the older version of polymer-build.

**Comment by justinfagnani** [comment] 2017-04-09 04:16
Does look like a dupe of #88. Closing.

**Closed by justinfagnani** 2017-04-09 04:16 UTC
