### ISSUE TITLE
Build failure for bundled site with app containing element with script file

### ISSUE THREAD

**Issue by srijken** [Polymer/polymer-build#78] opened 2016-11-15 16:30 UTC
### Description
I created an app that uses a (polymer based) custom element that references a javascript file. When building this I get a build error

### Versions & Environment
- polymer-build: 0.4.1
- node: 4.4.4
- Operating System: Windows 10 Version 1607

#### Steps to Reproduce
- Clone this repos: https://github.com/srijken/test-app
- `bower install`
- `polymer build`

Details:
- It uses this element: https://github.com/srijken/script-element
- The element includes another html file: https://github.com/srijken/script-element/blob/master/script-element.html#L2
- That html file includes a script: https://github.com/srijken/script-element/blob/master/hello-world.html#L1

I already tried using relative paths (see relative-paths branch of test-app), but that causes http 404 errors in the browser debug console when browsing to http://localhost:8080/foo/bar (routing elements are not included in the sample, but loading the page should work)

#### Expected Results
No error, and build output in both bundled and unbundled

#### Actual Results
```
info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Promise rejection: Error: file path is not in root: C:\Sources\Projects\bower_components\script-element\hello-world.js (C:\Sources\Projects\tmp2)
error:   Error: file path is not in root: C:\Sources\Projects\bower_components\script-element\hello-world.js (C:\Sources\Projects\tmp2)
    at Object.urlFromPath (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\path-transformers.js:41:15)
    at StreamAnalyzer.getFile (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:107:39)
    at StreamResolver.accept (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:210:34)
    at FileLoader.request (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\loader\file-loader.js:64:27)
    at Object.<anonymous> (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\vulcanize\lib\vulcan.js:318:26)
    at Array.map (native)
    at Object.inlineScripts (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\vulcanize\lib\vulcan.js:311:34)
    at Object.<anonymous> (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\vulcanize\lib\vulcan.js:458:21)
    at run (C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\core-js\modules\es6.promise.js:87:22)
    at C:\Users\s.rijken\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\core-js\modules\es6.promise.js:100:28
```

**Comment by rictic** [comment] 2016-11-15 19:50
I bet what's happening is that you've got a script tag that points to `script-element/hello-world.js' but it has one too many `../`'s in it. This will work in the browser because `../` from the path `/` is just `/`, so extra `../`'s are ignored, but when we map that back to the file system it looks like the import is trying to reach outside of your project's directory and we crash.

We should leave this issue open if if that's the case though, as we should be able to give a better error message than this using the Warnings system.

**Comment by FredKSchott** [comment] 2016-11-15 22:25
First of all, thank you for the thorough issue and isolated reproduction in the test-app repo. I can't tell you how much we appreciate it when someone takes the time to write something like this up.

A bunch of us debugged this further in the #tools slack channel, copy and pasting that here for completeness:

<details>
  <summary>Click to expand</summary>

srijken	[11:40 AM]  
I want to start looking into this: https://github.com/Polymer/polymer-build/issues/78, any recommendations what’s the best way to debug polymer-build?

justin	[11:42 AM]  
well, there's always printf-debugging :slightly_smiling_face: but the `--inspect` flag is very nice in node >6.3

rictic	[11:50 AM]  
@srijken Added a comment to your bug (edited)

srijken	[11:57 AM]  
right.. well there’s not an extra ../ somewhere as far as I can see, polymer serve, and unbundled both work
I wish it was that simple, still hope so :slightly_smiling_face:

srijken	[12:45 PM]  
I’m at a breakpoint now in the vulcanize code, there’s an extra leading `../` there. question is, what happens pre-vulcanize that touches the paths?

srijken	[1:18 PM]  
getting really close..
`pathPosix.relative('.', '/bower_components/script-element/hello-world.js');`
results in
`'../bower_components/script-element/hello-world.js`
on OSX it’s even worse/stranger:
```
path.posix.relative('.', '/bower/test')
'../../../bower/test'
```
(edited)

timvdlippe	[1:36 PM]  
Wow well done debugging @srijken !
You were right all along; explains why I could not find the issue either after looking on it for a long time :stuck_out_tongue:

srijken	[1:38 PM]  
not entirely sure where the problem is though
not sure why it’s calling .relative there in the first place (edited)
on OSX it’s worse, because there resolving /bower_components translate into: “give me the relative path to /bower_components (in the system root)"
so the deeper your project is, the more `../`‘s are added

timvdlippe	[1:41 PM]  
What line is the culprit in `polymer-build`?

srijken	[1:42 PM]  
either here, or inside that method: https://github.com/Polymer/vulcanize/blob/master/lib/pathresolver.js#L47
looks like abspath should be set?

timvdlippe	[1:44 PM]  
CC @fks for the amazing debugging report above

srijken	[1:44 PM]  
https://github.com/Polymer/vulcanize/blob/master/lib/pathresolver.js#L83
if it would call url.resolve there, that would be the correct outcome?

fks	[1:44 PM]  
Haha whoops, wish I'd seen this earlier
I was just digging in on my own, looks like I'm a few steps behind you :)

srijken	[1:45 PM]  
hehe

fks	[1:53 PM]  
yea I think you're spot on, something weird is happening vulcanize around there
when I add this line under L47: `console.log('RESOLVEPATHS', importUrl, mainDocUrl, attrValue, relUrl);`
I see this in the build:
```
RESOLVEPATHS /bower_components/script-element/hello-world.html /bower_components/script-element/script-element.html hello-world.js hello-world.js
RESOLVEPATHS /bower_components/script-element/script-element.html index.html hello-world.js ../../../../bower_components/script-element/hello-world.js
RESOLVEPATHS /src/tmp2-app/tmp2-app.html index.html ../../bower_components/script-element/ ../../../../bower_components/script-element
RESOLVEPATHS index.html index.html ../../../../src/tmp2-app/ ../../../../src/tmp2-app
```
looks like it's not just hello-world.js that's dying here

fks	[1:55 PM]  
but also that first line is correct, and it's the second, incorrect call to load `hello-world.js` that fails

srijken	[1:59 PM]  
@fks, you’re on non-windows?

fks	[2:00 PM]  
yea I'm on a mac

srijken	[2:00 PM]  
that explains the extra ../../.., becuase it’s trying to resolve to '/'
when you move it deeper one level, you get an extra ../
relative paths between the html and js files shouldn’t be impacted by the location of the project :wink:

fks	[2:02 PM]  
haha agreed
interesting find: everything is broken when mainDocUrl = `index.html`. Change it to `/index.html`, everything is fixed

srijken	[2:03 PM]  
interesting
that could provide a workaround, I was just running `polymer build`
confirmed that this results in a successful build: ` polymer build --entrypoint /index.html`

fks	[2:05 PM]  
ahhhhhhhhhhhhhhhhh
getting closer :)
one thing that might help you in debugging: we just moved to the new analyzer and a new configuration manager in the latest version of polymer-build
you can test it out on the CLI `next` branch via `npm install -g polymer-cli@next`
`polymer build --entrypoint /index.html` doesn't work on the new version, because it treats it as an absolute path

srijken	[2:10 PM]  
right

fks	[2:13 PM]  
I think I found it: vulcan.js L493-L505
 ```
  process: function process(target, cb) {
    if (this.inputUrl) {
      this._process(this.inputUrl, cb);
    } else {
      if (this.abspath) {
        target = pathPosix.resolve('/', target);
      } else {
        target = this.pathResolver.pathToUrl(path.resolve(target));
      }
      this._process(target, cb);
    }
  }
```
we're passing a `inputUrl` option when we create our Vulcanize instance for build
which is created via `pathTransformers.urlFromPath(this.config.root, fragment)`
so `/Users/fschott/Code/test-app/index.html` becomes `index.html`, which is bad
(or at least bad in our code, it probably should still work that way)
</details>

**Comment by FredKSchott** [comment] 2016-11-15 22:39
I think we've just got the vulcanize options wrong. My guess is that we need to pass the application `config.root` into vulcanize via the `abspath` option so that it knows  which folder to treat as "webroot" and that target is an absolute path within the application.

**Closed** 2016-12-07 01:32 UTC
