### ISSUE TITLE
Bundler causes rejoining of original streams instead of modified ones

### ISSUE THREAD

**Issue by tony19** [Polymer/polymer-build#110] opened 2017-01-17 21:41 UTC
### Description
When the build stream is passed through the bundler, the result contains the original split streams instead of the modified ones (e.g., processed by `uglify` or other minifiers).

### Versions & Environment
- polymer-build: 0.6.0
- node: 7.4.0
- Operating System: macOS Sierra 10.12

#### Steps to Reproduce

 1. Generate project from [`generator-polymer-init-custom-build` 2.0.0](https://github.com/PolymerElements/generator-polymer-init-custom-build/releases/tag/v2.0.0).
 
 2. Install `gulp-uglify`:

        yarn add -D gulp-uglify

 3. Edit the project's `gulpfile.js` to use `gulp-uglify`, and uncomment [`gulpfile.js:46`](https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/bb033e5/generators/app/gulpfile.js#L46), which runs `uglify`:

        const uglify = require('gulp-uglify');
        ...

        function build() {
          ...
          let sourcesStream = polymerProject.sources()
            .pipe(gulpif(/\.js$/, uglify()))

 4. Run `gulp build`.
 5. Observe the output of `build/src/my-view1.html` does **not** contain minified JS.
 6. Comment out [`gulpfile.js:69`](https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/bb033e5/generators/app/gulpfile.js#L69), which pipes the build through the bundler:

        buildStream = buildStream.pipe(polymerProject.bundler);

 7. Run `gulp build`.
 8. Observe the output of `build/src/my-view1.html` contains minified JS.

#### Expected Results
Output files contain modified streams.

For example, minified JS like this:

```html
<script>Polymer({is:"my-view1"});let foo=1;console.log(foo++);</script>
```

#### Actual Results
Output files contain original/unmodified streams from `HTMLSplitter`.

For example:

```html
<script>
  Polymer({
    is: 'my-view1',
  });

  let foo = 1;
  console.log(foo++);
</script>
```

**Comment by tony19** [comment] 2017-01-17 22:05
fyi, the `polymer-bundler` branch (from #108) didn't fix the bug in my tests :(

**Comment by davidsteinberger** [comment] 2017-01-18 17:04
Just setting up a new project and ran into the exact same issue. Does anyone how to fix the bundler?

**Comment by FredKSchott** [comment] 2017-01-18 19:45
This was brought up in https://github.com/Polymer/polymer-build/issues/93 We are waiting on #108 to fix this since it moves us to the new bundler. Once that's in place, we can make sure it's getting the right files.

@tony19 link to the issue with the bugs that you're seeing?

**Comment by davidsteinberger** [comment] 2017-01-18 20:37
@FredKSchott thanks for the explanation. Have u got a rough idea when #108 is going to land?

**Comment by FredKSchott** [comment] 2017-01-18 22:04
Both @usergenic and I are working on it all this week. If anyone would like to contribute a code review as well, feel free!

**Comment by davidsteinberger** [comment] 2017-01-24 21:45
Is there any workaround until the new bundler lands? I tried crisper w/ vulcanize but that didn't workout too well, I guess b/c of the PRPL structure of the app.

**Comment by FredKSchott** [comment] 2017-01-24 23:16
Running optimizers *after* the bundler is the current work around.

**Comment by abdonrd** [comment] 2017-01-31 11:58
I'm also having problems with this. Something new?

**Comment by abdonrd** [comment] 2017-02-15 23:57
Friendly ping. :)

**Comment by FredKSchott** [comment] 2017-02-16 17:57
@usergenic has this on his radar but is juggling some other things as well. If anyone wants to take over and create a PR in the mean time I would be happy to help advise

**Comment by stramel** [comment] 2017-02-18 21:41
Seems like `v0.8.1` will work?

**Comment by FredKSchott** [comment] 2017-02-19 20:32
@stramel no fix for this has been released yet / in v0.8.1.

**Comment by web-padawan** [comment] 2017-02-19 20:39
BTW, what is the benefit of running optimizers before bundling? I mean, splitting and rejoining lot of files (e. g. 300+ elements) is slower than post-processing of few bundles, isn't it?

**Comment by FredKSchott** [comment] 2017-02-19 20:55
Optimizing before bundle lets you process your source files and dependencies separately. So if you wanted to use something like babel to compile your sources only, you can.

If you aren't handling your sources and dependencies separately, optimizing after bundling will probably give you a performance boost.

**Comment by stramel** [comment] 2017-02-20 01:13
@FredKSchott Oops! You're correct, I think I got a bit over excited about the new release. Can't wait until this is fixed!

**Comment by myw** [comment] 2017-02-22 08:11
@FredKSchott that is exactly my workflow: babel + bundle. The current state of things makes it impossible—since I can't babel, my only workaround is to not bundle 😢

**Comment by web-padawan** [comment] 2017-02-22 08:37
@myw you can use babel, why not? Just use following workflow: bundle - crisper - babel. See [here](https://github.com/web-padawan/pack/blob/master/gulpfile.js#L273) and below my example (a bit outdated, since it doesn't use `polymer-build` yet, as I used to make bundles via `web-component-shards` previously).

**Comment by myw** [comment] 2017-02-22 09:38
@web-padawan yes, that was the old workflow, even with `polymer-build`, somewhere around 0.4. I mistyped earlier: I meant to say, since I can't _not_ babel

**Comment by tjmonsi** [comment] 2017-02-23 08:47
@myw would it be possible to use two streams then? like the analyzer being used to analyze the original stream and then bundle the modified stream (like after babel). I would like to know where in the files where this works so I can look at it as well...

**Comment by myw** [comment] 2017-02-23 16:50
@tjmonsi the problem is you can't get the stream without calling the analyzer

**Closed** 2017-03-07 20:43 UTC

**Comment by stramel** [comment] 2017-03-07 23:03
Is there going to be a tag soon for @usergenic's awesome fix?
